// Action type constants for table state
export const SET_DATA = 'SET_DATA';
export const SET_SORTING = 'SET_SORTING';
export const SET_GLOBAL_FILTER = 'SET_GLOBAL_FILTER';
export const SET_COLUMN_FILTER = 'SET_COLUMN_FILTER';
export const SET_PAGINATION = 'SET_PAGINATION';
export const TOGGLE_ROW_SELECTION = 'TOGGLE_ROW_SELECTION';
export const SET_SELECTED_IDS = 'SET_SELECTED_IDS';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const SELECT_ALL_ON_PAGE = 'SELECT_ALL_ON_PAGE';
export const DESELECT_ALL_ON_PAGE = 'DESELECT_ALL_ON_PAGE';
export const DELETE_SELECTED = 'DELETE_SELECTED';

export default {
  SET_DATA,
  SET_SORTING,
  SET_GLOBAL_FILTER,
  SET_COLUMN_FILTER,
  SET_PAGINATION,
};
